export const USER_LOGIN_DETAIL_SUCCESS = 'USER_LOGIN_DETAIL_SUCCESS';
export const PLANET_DETAIL_SUCCESS = "PLANET_DETAIL_SUCCESS";
export const PLANET_SINGLE_DETAIL_SUCCESS = "PLANET_SINGLE_DETAIL_SUCCESS";
export const FILMS_RESULT_SUCCESS = "FILMS_RESULT_SUCCESS";
export const FILMS_RESULT_FAILS = "FILMS_RESULT_FAILS";

export const POST_RESULT_SUCCESS = "POST_RESULT_SUCCESS";
export const POST_DETAIL_SUCCESS = "POST_DETAIL_SUCCESS";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DETAIL_COMMENT_SUCCESS = "POST_DETAIL_COMMENT_SUCCESS";